#!/bin/bash

which unzip > /dev/null
if [ $? -ne 0 ]; then
echo "ERROR:  unzip is missing"
exit 111
fi

export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
source $ATLAS_LOCAL_ROOT_BASE/user/atlasLocalSetup.sh "" 
localSetupDQ2Client --skipConfirm

unzip -o $0 > /dev/null 2>&1
PYNAME=`echo $0 | sed -e "s/\(-.*$\)/.py/"`
exec python -u $PYNAME "$@"

