#!/bin/bash

which unzip > /dev/null
if [ $? -ne 0 ]; then
echo "ERROR:  unzip is missing"
exit 111
fi

unzip -o $0 > /dev/null 2>&1
PYNAME=`echo $0 | sed -e "s/\(-.*$\)/.py/"`

if command -v python &> /dev/null
then
    PY_COMMAND=python
else
    if command -v python3 &> /dev/null
    then
        PY_COMMAND=python3
    else
        PY_COMMAND=python2
    fi
    mkdir tmp_bin
    ln -fs `which $PY_COMMAND` tmp_bin/python
    export PATH=$PWD/tmp_bin:$PATH
fi

echo using $PY_COMMAND

exec python -u $PYNAME "$@"
